apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  namespace: {{ .Values.pod.namespace }}
spec:
  containers:
    - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      name: {{ .Values.pod.containerName }}
  serviceAccountName: {{ .Values.serviceAccount.name }}
  terminationGracePeriodSeconds: {{ .Values.pod.terminationGracePeriodSeconds }}
