image:
  repository: ghcr.io/syossan27/pre-oom-killer
  tag: latest

pod:
  name: pre-oom-killer
  namespace: kube-system
  containerName: pre-oom-killer
  terminationGracePeriodSeconds: 30

serviceAccount:
  name: pre-oom-killer
  namespace: kube-system

rbac:
  name: pre-oom-killer